kind: Service
apiVersion: v1
metadata:
# set your user name
  name: user10-hello-world
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
# set your user name
    app: user10-hello-world