deploy: 
  service:
    servicePort: 8081

deploy1: 
  ReplicaNumber: 1

  containers:
      containerPort: 8081
      image: 'quay.io/argo-helm-workshop/workshop-app'
      tag: 'chart_v2'

  argocd:
    syncwave:
      deployment: 5
      configmap: 1

  service:
      servicePort: 8081

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8081
    image: 'quay.io/argo-helm-workshop/workshop-app'
    tag: 'chart_v2'

  argocd:
    syncwave:
      deployment: 10
      configmap: 1

  service:
    servicePort: 8081